#!/usr/bin/env bash
set -euo pipefail

BASE_MODEL="${BASE_MODEL:-/root/autodl-tmp/models/Qwen2.5-3B-Instruct}"
REPORT_TO="${REPORT_TO:-wandb}"
WANDB_PROJECT="${WANDB_PROJECT:-text2sql-posttraining}"
RUN_NAME="${RUN_NAME:-qwen25_3b_sft_v1}"
HF_ENDPOINT="${HF_ENDPOINT:-https://hf-mirror.com}"
HF_HOME="${HF_HOME:-/root/autodl-tmp/hf-home}"
HUGGINGFACE_HUB_CACHE="${HUGGINGFACE_HUB_CACHE:-/root/autodl-tmp/hf-cache}"
TRANSFORMERS_CACHE="${TRANSFORMERS_CACHE:-/root/autodl-tmp/transformers-cache}"
OMP_NUM_THREADS="${OMP_NUM_THREADS:-8}"
MKL_NUM_THREADS="${MKL_NUM_THREADS:-8}"
TRAIN_BATCH_SIZE="${TRAIN_BATCH_SIZE:-8}"
EVAL_BATCH_SIZE="${EVAL_BATCH_SIZE:-2}"
GRADIENT_ACCUMULATION_STEPS="${GRADIENT_ACCUMULATION_STEPS:-4}"
MODEL_MAX_LENGTH="${MODEL_MAX_LENGTH:-1024}"
NUM_TRAIN_EPOCHS="${NUM_TRAIN_EPOCHS:-2}"
LEARNING_RATE="${LEARNING_RATE:-2e-5}"
LOGGING_STEPS="${LOGGING_STEPS:-20}"
EVAL_STEPS="${EVAL_STEPS:-200}"
SAVE_STEPS="${SAVE_STEPS:-400}"
PREPROCESSING_NUM_WORKERS="${PREPROCESSING_NUM_WORKERS:-8}"
DATALOADER_NUM_WORKERS="${DATALOADER_NUM_WORKERS:-4}"
GRADIENT_CHECKPOINTING="${GRADIENT_CHECKPOINTING:-True}"
LOG_FILE="${LOG_FILE:-logs/${RUN_NAME}.log}"

mkdir -p logs cache
mkdir -p "$HF_HOME" "$HUGGINGFACE_HUB_CACHE" "$TRANSFORMERS_CACHE"

export BASE_MODEL
export REPORT_TO
export WANDB_PROJECT
export RUN_NAME
export HF_ENDPOINT
export HF_HUB_ENABLE_HF_TRANSFER=0
export HF_HUB_DISABLE_TELEMETRY=1
export HF_HUB_DISABLE_XET=1
export HF_HOME
export HUGGINGFACE_HUB_CACHE
export TRANSFORMERS_CACHE
export OMP_NUM_THREADS
export MKL_NUM_THREADS
export TRAIN_BATCH_SIZE
export EVAL_BATCH_SIZE
export GRADIENT_ACCUMULATION_STEPS
export MODEL_MAX_LENGTH
export NUM_TRAIN_EPOCHS
export LEARNING_RATE
export LOGGING_STEPS
export EVAL_STEPS
export SAVE_STEPS
export PREPROCESSING_NUM_WORKERS
export DATALOADER_NUM_WORKERS
export GRADIENT_CHECKPOINTING

echo "[run_sft_all] RUN_NAME=$RUN_NAME"
echo "[run_sft_all] BASE_MODEL=$BASE_MODEL"
echo "[run_sft_all] TRAIN_BATCH_SIZE=$TRAIN_BATCH_SIZE"
echo "[run_sft_all] GRADIENT_ACCUMULATION_STEPS=$GRADIENT_ACCUMULATION_STEPS"
echo "[run_sft_all] LOG_FILE=$LOG_FILE"

bash scripts/run_sft.sh 2>&1 | tee "$LOG_FILE"
